routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Helpers\Brand;
use Illuminate\Http\Request;

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('/login-failed', function () {
    return view('auth.fail');
});

Route::get('/', function () {
    return view(config('app.prefix') . '.home.index');
})->name('home');

// Password Reset Routes
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// User Management Routes
Route::resource('/user', 'UserManagementController');

// User Profile Routes
Route::get('/profile', 'UserProfileController@index')->name('userProfile.index');
Route::get('/profile/edit', 'UserProfileController@edit')->name('userProfile.edit');
Route::patch('/profile/update', 'UserProfileController@update')->name('userProfile.update');

Route::get('/profile/password', 'ChangePasswordController@index')->name('changePassword.index');
Route::post('/changePassword', 'ChangePasswordController@changePassword')->name('changePassword.changePassword');

// Contact
Route::resource('/contact', 'ContactController');
Route::post('/air2PostContact', 'ContactController@a2PStoreContact')->name('air2PostContact');
// Route::get('/contact', function () {
//     return view(config('app.prefix').'.contact.index');
// })->name('contact');

Route::post('/generalContact', 'GeneralContactController@sendEmail')->name('generalContact');

// Careers
Route::resource('/careers', 'CareerController');
Route::get('/careers/delete/{id}', 'CareerController@delete')->name('careers.delete');

// Blog Public
Route::get('/blog', 'BlogController@index')->name('blog.index');
Route::get('/blog/{blog}', 'BlogController@show')->name('blog.show');

// Pages
Route::get('/pages/{pages}/restore', 'PageController@restore')->name('pages.restore');
Route::resource('/pages', 'PageController');
Route::get('/pages/delete/{pages}', 'PageController@delete')->name('pages.delete');

// Image Uploads
Route::get('/api/images', 'ImageUploadController@index');
Route::post('/api/images/store', 'ImageUploadController@store');

// Services
Route::get('/services', function () {
    return view(config('app.prefix') . '.services.index');
})->name(config('app.prefix') . '.services');

// Software
Route::get('/software', function () {
    return view(config('app.prefix') . '.software.index');
})->name(config('app.prefix') . '.software');

// Services
Route::get('/process', function () {
    return view(config('app.prefix') . '.process.index');
})->name(config('app.prefix') . '.process');

// Technology
Route::get('/technology', function () {
    return view(config('app.prefix') . '.technology.index');
})->name(config('app.prefix') . '.technology');

// Process
Route::get('/process', function () {
    return view(config('app.prefix') . '.process.index');
})->name(config('app.prefix') . '.process');

// About
Route::get('/about', function () {
    return view(config('app.prefix') . '.about.index');
})->name(config('app.prefix') . '.about');

// Supply Chain

Route::get('/tracking', function () {
    return redirect('https://pipeline.flatworldsc.com/app.php?r=tracking');
});
Route::post('/getTracking', 'ShipmentTrackingController@getTracking')->name('getTracking');

// Solutions
Route::get('/solutions', function () {
    return view(config('app.prefix') . '.solutions.index');
})->name(config('app.prefix') . '.solutions');

Route::get('/solutions/ltl', function () {
    return view(config('app.prefix') . '.solutions.ltl');
})->name(config('app.prefix') . '.solutions.ltl');

Route::get('/solutions/tl', function () {
    return view(config('app.prefix') . '.solutions.tl');
})->name(config('app.prefix') . '.solutions.tl');

Route::get('/solutions/hospitality', function () {
    return view(config('app.prefix') . '.solutions.hospitality');
})->name(config('app.prefix') . '.solutions.hospitality');

Route::get('/solutions/expedited', function () {
    return view(config('app.prefix') . '.solutions.expedited');
})->name(config('app.prefix') . '.solutions.expedited');

Route::get('/solutions/international', function () {
    return view(config('app.prefix') . '.solutions.international');
})->name(config('app.prefix') . '.solutions.international');

Route::get('/solutions/returns', function () {
    return view(config('app.prefix') . '.solutions.returns');
})->name(config('app.prefix') . '.solutions.returns');


// Flat World Global Solutions
Route::get('/solutions/air2post', function () {
    return view(config('app.prefix') . '.solutions.air2post');
})->name(config('app.prefix') . '.solutions.air2post');

Route::get('/solutions/airFreight', function () {
    return view(config('app.prefix') . '.solutions.airFreight');
})->name(config('app.prefix') . '.solutions.airFreight');

Route::get('/solutions/oceanFreight', function () {
    return view(config('app.prefix') . '.solutions.oceanFreight');
})->name(config('app.prefix') . '.solutions.oceanFreight');

Route::get('/solutions/compliance', function () {
    return view(config('app.prefix') . '.solutions.compliance');
})->name(config('app.prefix') . '.solutions.compliance');

Route::get('/solutions/tempControlledCargo', function () {
    return view(config('app.prefix') . '.solutions.tempControlledCargo');
})->name(config('app.prefix') . '.solutions.tempControlledCargo');

Route::get('/solutions/specialtyCargo', function () {
    return view(config('app.prefix') . '.solutions.specialtyCargo');
})->name(config('app.prefix') . '.solutions.specialtyCargo');

Route::get('/solutions/warehousing', function () {
    return view(config('app.prefix') . '.solutions.warehousing');
})->name(config('app.prefix') . '.solutions.warehousing');

Route::get('/solutions/domesticTransportation', function () {
    return view(config('app.prefix') . '.solutions.domesticTransportation');
})->name(config('app.prefix') . '.solutions.domesticTransportation');

Route::get('/solutions/shipmentTracking', function () {
    return view(config('app.prefix') . '.solutions.shipmentTracking');
})->name(config('app.prefix') . '.solutions.shipmentTracking');

Route::get('/terms', function () {
    return view(config('app.prefix') . '.termsConditions.index');
})->name(config('app.prefix') . '.terms');

Route::get('/resources', function () {
    return view(config('app.prefix') . '.resources.index');
})->name(config('app.prefix') . '.resources');

// E-Commerce Routes
Route::get('/ecommerce', function () {
    return view(config('app.prefix') . '.solutions.ecommerce');
})->name(config('app.prefix') . '.ecommerce');

Route::get('/solutions/ecommerceQuote/lineItem', function () {
    return view(config('app.prefix') . '.solutions.ecommerceQuote.lineItem');
})->name(config('app.prefix') . '.ecommerce.lineItem');

Route::get('/solutions/ecommerceQuote/cartonCrate', function () {
    return view(config('app.prefix') . '.solutions.ecommerceQuote.cartonCrate');
})->name(config('app.prefix') . '.ecommerce.cartonCrate');

Route::get('/solutions/ecommerceQuote/cartonPallet', function () {
    return view(config('app.prefix') . '.solutions.ecommerceQuote.cartonPallet');
})->name(config('app.prefix') . '.ecommerce.cartonPallet');

Route::post('/eCommerceForm', 'ECommerceFormController@sendEmail')->name('eCommerceForm');

Route::get('/profile/signatures/download/{signature}', 'EmailSignatureController@renderHtml')->name('signatures.download');
Route::resource('/profile/signatures', 'EmailSignatureController');

Auth::routes();

Route::get('/playground', function () {
    return view('playground');
})->name('playground');

Route::get('/api/companies', 'CompanyController@index');

// Route::get('/', 'HomeController@index')->name('home');

// Temp routes
Route::get('/alert', function () {
    return view(config('app.prefix') . '.alerts.indiaAlert');
});

// Api
Route::namespace('Api')->name('api.')->prefix('api')->group(function () {
    // Blog Routes
    Route::get('blog/{blog}/restore', 'BlogApiController@restore')->name('blog.restore');
    Route::get('blog/{blog}/delete', 'BlogApiController@delete')->name('blog.delete');
    Route::resource('blog', 'BlogApiController');

    // Career Routes
    Route::resource('career', 'CareerController');

    // Tracking
    Route::post('tracking/{trackingNumber}', 'TrackingApiController@getTracking')->name('tracking');
});

Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () {
    // Blog Admin
    Route::resource('blog', 'BlogAdminController');

    // Career Admin
    Route::resource('career', 'CareerController');
});

// Temp route to test emails
Route::get('mailable', function (Request $request) {
    return new App\Mail\EcommerceResponderForm($request);
})->name('mailable');

// Temp routes
Route::get('/review-map', function () {
    return view('temp.review');
});

app/Career.php
<?php

namespace App;

use App\Traits\Filters\FilterByCompanyTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Career extends Model
{

    use SoftDeletes;
    use FilterByCompanyTrait;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */

    protected $dates = ['deleted_at'];

    protected $fillable = ['company_id', 'published', 'title', 'short_description', 'long_description', 'created_by', 'updated_by'];

    public function company()
    {
        return $this->belongsTo('App\Company', 'company_id', 'id');
    }
}

app/Http/Controllers/Admin/CareerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Career;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CareerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $careers = Career::where('company_id', 1)->get();

        return view('admin.career.index', [
            'careers' => $careers,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.career.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function show(Career $career)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function edit(Career $career)
    {
        return view('admin.career.edit', [
            'career' => $career
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Career $career)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function destroy(Career $career)
    {
        //
    }
}

app/Http/Controllers/Api/CareerController.php
<?php

namespace App\Http\Controllers\Api;

use App\Career;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Validator;
use Auth;

class CareerController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:developer|super.admin')->only('restore');
        $this->middleware('role:developer|super.admin|hr')->only(['create', 'store', 'edit', 'update', 'delete']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $careers = Career::with('company')
            ->orderBy('created_at', 'desc')
            ->get();

        return response()->json([
            'careers' => $careers,
        ])->setStatusCode(200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'title' => 'required',
            'published' => 'required',
            'short_description' => 'required|max:255',
            'long_description' => 'required',
        ];

        $messages = [
            'title.required' => 'A title is required',
            'published.required' => 'Please set the published state',
            'short_description.required' => 'A description is required.',
            'short_description.max' => 'Please enter a shorter description',
            'long_description.required' => 'A long description is required.',
        ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()) {
            return response()->json([
                'errorBag' => $validator->errors(),
                'oldInput' => $request->all(),
            ]);
        }

        try {
            DB::beginTransaction();
            $career = new Career;
            $career->fill($request->all());
            // Todo: make company_id dynamic.
            $career->company_id = 1;
            $career->created_by = Auth::user()->id;
            $career->saveOrFail();
            DB::commit();
        } catch (\Throwable $th) {
            return $th;
            DB::rollback();
        }

        return response()->json([
            'career' => $career ?? null,
        ])->setStatusCode(200);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function show(Career $career)
    {
        return response()->json([
            'career' => $career,
        ])->setStatusCode(200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function edit(Career $career)
    {
        return response(json_encode([
            'career' => $career
        ]), 200);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Career $career)
    {
        $rules = [
            'title' => 'required',
            'published' => 'required',
            'short_description' => 'required|max:255',
            'long_description' => 'required',
        ];

        $messages = [
            'title.required' => 'A title is required',
            'published.required' => 'Please set the published state',
            'short_description.required' => 'A description is required.',
            'short_description.max' => 'Please enter a shorter description',
            'long_description.required' => 'A long description is required.',
        ];


        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()) {
            return response()->json([
                'errorBag' => $validator->errors(),
            ]);
        }

        try {
            DB::beginTransaction();
            $career = Career::where('id', $request->id)->firstOrFail();
            $career->fill($request->all());
            $career->updated_by = Auth::user()->id;
            $career->save();
            DB::commit();
        } catch (\Throwable $th) {
            throw $th;
            DB::rollback();
        }

        return response(json_encode([
            'career' => $career,
            'message' => 'Successfully updated the career listing.'
        ]), 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Career  $career
     * @return \Illuminate\Http\Response
     */
    public function destroy(Career $career)
    {
        try {
            DB::beginTransaction();
            $career->delete();
            $career->save();
            DB::commit();
            $message = 'Successfully deleted the career listing.';
        } catch (\Throwable $th) {
            throw $th;
            DB::rollback();
        }

        return redirect()->back();
    }
}

resources/views/careers/create.blade.php
@extends('app.updated-layout')

@section('title', '[New] Career Listing | ')

@section('content')

    @if ($errors->any())
    <div class="message-flash critical">
        <span class="close" data-toggle="hide-parent">
            <fw-font-awesome-icon icon="times"></fw-font-awesome-icon>
            {{-- <i class="far fa-times fa-fw"></i> --}}
        </span>
        <div>
            @foreach ($errors->all() as $error)
            <span class="response__heading" style="display: block; text-align: left;">{{ $error }}</span>
            @endforeach
        </div>
    </div>
    @endif

    <h1 class="blog__title">Create New Career Listing</h1>

    <form action="{{ route('careers.store') }}" method="POST" enctype="multipart/form-data">

        @csrf

        <div class="form-group">
            <label for="title" @if ($errors->has('title')) class="error" @endif>
                <span class="label-text">Career Title</span>
                <input type="text" name="title" id="title" value="{{ old('title') }}" placeholder="Post Title" required>
            </label>
        </div>

        <div class="form-group">
            <label for="short_description" @if ($errors->has('short_description')) class="error" @endif>
                <span class="label-text label-text--textarea">Short Description</span>
                <textarea name="short_description" id="short_description" rows="3" placeholder="Drop in a short description about this post." required>{{ old('short_description') }}</textarea>
            </label>
        </div>

        <div class="form-group">
            <label for="long_description" @if ($errors->has('long_description')) class="error" @endif>
                <div class="label-text label-text--textarea">Long Description</div>
                <textarea name="long_description" id="long_description" rows="10" placeholder="Please be as descriptive as possible." required>{{ old('long_description') }}</textarea>
            </label>
        </div>

        @role(['developer', 'super.admin', 'hr'])
        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">What company does this need to post on?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('company')) class="error" @endif>
                @foreach($companies as $company)
                <label class="radio" for="{{ $company->shortname }}">
                    <input type="radio" name="{{ $company->shortname }}" id="{{ $company->shortname }}" value="{{ $company->id }}" required>
                    <span class="label-text">{{ $company->name }}</span>
                </label>
                @endforeach
            </fieldset>
        </div>
        @endrole



        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Do you want this to post now?</h2>

        <div class="">
            <fieldset @if ($errors->has('published')) class="error" @endif>
                <label class="radio" for="published">
                    <input type="radio" name="published" id="published" value="1" required>
                    <span class="label-text">Published</span>
                </label>
                <label class="radio" for="draft">
                    <input type="radio" name="published" id="draft" value="0" required>
                    <span class="label-text">Draft</span>
                </label>
            </fieldset>
        </div>

        <div style="display: flex; flex-flow: row nowrap; justify-content: flex-end; margin: 12px 0 0; padding: 0 12px;">
            <fw-link href="{{ route('careers.index') }}" design="text" state="critical" size="small" icon="times" style="margin: 0 16px 0 0;">
                Cancel
            </fw-link>

            <fw-button design="solid" state="info" size="small" icon="paper-plane" type="submit" role="button">
                Create Career Listing
            </fw-button>
        </div>

    </form>

@endsection

resources/views/careers/edit.blade.php
@extends('app.updated-layout')

@section('title', '[New] Career Listing | ')

@section('content')

    @if ($errors->any())
    <div class="message-flash critical">
        <span class="close" data-toggle="hide-parent">
            <fw-font-awesome-icon icon="times"></fw-font-awesome-icon>
            {{-- <i class="far fa-times fa-fw"></i> --}}
        </span>
        <div>
            @foreach ($errors->all() as $error)
            <span class="response__heading" style="display: block; text-align: left;">{{ $error }}</span>
            @endforeach
        </div>
    </div>
    @endif

    <h1 class="blog__title">Edit {{ $career->title }}</h1>

    <form action="{{ route('careers.update', ['career' => $career->id]) }}" method="POST" enctype="multipart/form-data">
        @method('PATCH')
        @csrf

        <div class="form-group">
            <label for="title">
                <span class="label-text">Career Title</span>
                <input type="text" name="title" id="title" value="{{ $career->title }}" placeholder="Post Title" required>
            </label>
        </div>

        <div class="form-group">
            <label for="short_description">
                <span class="label-text label-text--textarea">Short Description</span>
                <textarea name="short_description" id="short_description" rows="3" placeholder="Drop in a short description about this post." required>{{ $career->short_description }}</textarea>
            </label>
        </div>

        <div class="form-group">
            <label for="long_description">
                <span class="label-text label-text--textarea">Long Description</span>
                <textarea name="long_description" id="long_description" rows="10" placeholder="Please be as descriptive as possible." required>{{ $career->long_description }}</textarea>
            </label>
        </div>

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">What company does this need to post on?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('company')) class="error" @endif>
                @foreach($companies as $company)
                <label class="radio" for="{{ $company->shortname }}">
                    @if($company->id == $career->company_id)
                    <input type="radio" name="{{ $company->shortname }}" id="{{ $company->shortname }}" value="{{ $company->id }}" checked required>
                    @else
                    <input type="radio" name="{{ $company->shortname }}" id="{{ $company->shortname }}" value="{{ $company->id }}" required>
                    @endif
                    <span class="label-text">{{ $company->name }}</span>
                </label>
                @endforeach
            </fieldset>
        </div>

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Do you want this to post now?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('published')) class="error" @endif>
                <label class="inputGroup radio" for="published">
                    @if ($career->published === 1)
                    <input type="radio" name="published" id="published" value="1" checked required>
                    @else
                    <input type="radio" name="published" id="published" value="1" required>
                    @endif
                    <span class="label-text">Published</span>
                </label>

                <label class="inputGroup radio" for="draft">
                    @if ($career->published === 0)
                    <input type="radio" name="published" id="draft" value="0" checked required>
                    @else
                    <input type="radio" name="published" id="draft" value="0" required>
                    @endif
                    <span class="label-text">Draft</span>
                </label>
            </fieldset>
        </div>

        <div style="display: flex; flex-flow: row nowrap; justify-content: flex-end; margin: 12px 0 0; padding: 0 12px;">
            <fw-link href="{{ route('careers.index') }}" design="text" state="critical" size="small" icon="times" style="margin: 0 16px 0 0;">
                Cancel
            </fw-link>

            <fw-button design="solid" state="info" size="small" icon="paper-plane" type="submit" role="button">
                Update Career Listing
            </fw-button>
        </div>

    </form>

@endsection

resources/views/careers/index.blade.php
@extends('app.updated-layout')
@section('title', 'Careers | ')
@section('content')

<h1 class="page__title my-1">Careers</h1>

<h3 class="page__subTitle my-1">We're looking for enthusiastic, motivated people to join our team at one of St. Louis’ fastest growing companies.</h3>

<div class="d-flex flex-column">
    <div class="splashImage" id="pipeline">
        <h3>Excellent people are at the heart of what we can accomplish</h3>
        <h3 class="em">enthusiastic, motivated people</h3>

        <img src="{{ asset('images/happy-business-meeting.jpg') }}" class="imageBg cover top" alt="">
    </div>
</div>

<div style="width: 100%; display: flex; flex-flow: row nowrap; justify-content: center; align-items: center; margin: 0 auto; padding: 0 0 48px;">
    <a href="/blog/116">
        <img src="{{ asset('images/topWorkplace2019.jpg') }}" alt="" style="max-width: 200px; width: 100%;">
    </a>

    <div style="padding: 12px 16px;">
        <a href="/blog/116" class="link" style="font-size: 16px; font-weight: 600; color: rgba(0,0,0,.65);">Learn about how we were ranked in the top 150 companies to work for in Saint Louis.</a>
    </div>
</div>

<ul class="generalList styled">
    <li>Industry competitive salaries</li>
    <li>New business incentives for sales positions</li>
    <li>Generous 401K matching</li>
    <li>100% paid premiums on health insurance</li>
    <li>Profit Sharing</li>
</ul>

<p class="text dark left paragraph general">
    Fast growing means opportunity, recognition and advancement. We're building on our culture of excellence and we're driven to exceed our customer's expectations as well as our own. Our customers aren't just clients, they're our partners.
</p>

<div class="d-flex flex-row flex-wrap justify-content-around mt-5">
    @if ($careers->isEmpty())
    <h1 style="text-align: center; color: hsla(205, 10%, 35%, 1);">Sorry! We don't currently have any positions available.</h1>

    @else

        @foreach($careers as $career)
        <fw-card-blog title="{{ $career->title }}" summary="{{ $career->short_description }}" company="{{ $career->company->name }}"
            created-at="{{ $career->created_at }}" href="{{ route('careers.show', ['career' => $career->id]) }}">
        </fw-card-blog>
        @endforeach
    @endif
</div>
@endsection

resources/views/careers/show.blade.php
@extends('app.updated-layout')

@section('title', $career->title.' | Careers | ')

@section('meta')
<meta property="og:title" content="{{ $career->title }}">
<meta property="og:description" content="{{ $career->short_description }}">
<meta property="og:site_name" content="{{ config('app.name') }}">
@endsection

@section('content')
<div class="blog__content" style="margin: 3rem 0 0;">
  <h1 class="blog__title">{{ $career->title }}</h1>

  <h3 class="blog__summary">{{ $career->short_description }}</h3>

  <div class="blog__meta">
      Posted on
      <span>{{ date('F d, Y', strtotime($career->created_at)) }}</span>
  </div>

  <div class="addthis_inline_share_toolbox" style="margin: 0 0 0 -7px;"></div>

  <hr
      style="
          border-color: rgba(0,0,0,.1);
          border-width: 1px;
          border-bottom: none;
      "
  >

  <div class="blog__body markdown">
      @markdown($career->long_description)
  </div>
</div>
@endsection

@section('footer-scripts')
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c4a2f08a740f59b"></script>
@endsection