routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Helpers\Brand;
use Illuminate\Http\Request;

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('/login-failed', function () {
    return view('auth.fail');
});

Route::get('/', function () {
    return view(config('app.prefix') . '.home.index');
})->name('home');

// Password Reset Routes
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// User Management Routes
Route::resource('/user', 'UserManagementController');

// User Profile Routes
Route::get('/profile', 'UserProfileController@index')->name('userProfile.index');
Route::get('/profile/edit', 'UserProfileController@edit')->name('userProfile.edit');
Route::patch('/profile/update', 'UserProfileController@update')->name('userProfile.update');

Route::get('/profile/password', 'ChangePasswordController@index')->name('changePassword.index');
Route::post('/changePassword', 'ChangePasswordController@changePassword')->name('changePassword.changePassword');

// Contact
Route::resource('/contact', 'ContactController');
Route::post('/air2PostContact', 'ContactController@a2PStoreContact')->name('air2PostContact');
// Route::get('/contact', function () {
//     return view(config('app.prefix').'.contact.index');
// })->name('contact');

Route::post('/generalContact', 'GeneralContactController@sendEmail')->name('generalContact');

// Careers
Route::resource('/careers', 'CareerController');
Route::get('/careers/delete/{id}', 'CareerController@delete')->name('careers.delete');

// Blog Public
Route::get('/blog', 'BlogController@index')->name('blog.index');
Route::get('/blog/{blog}', 'BlogController@show')->name('blog.show');

// Pages
Route::get('/pages/{pages}/restore', 'PageController@restore')->name('pages.restore');
Route::resource('/pages', 'PageController');
Route::get('/pages/delete/{pages}', 'PageController@delete')->name('pages.delete');

// Image Uploads
Route::get('/api/images', 'ImageUploadController@index');
Route::post('/api/images/store', 'ImageUploadController@store');

// Services
Route::get('/services', function () {
    return view(config('app.prefix') . '.services.index');
})->name(config('app.prefix') . '.services');

// Software
Route::get('/software', function () {
    return view(config('app.prefix') . '.software.index');
})->name(config('app.prefix') . '.software');

// Services
Route::get('/process', function () {
    return view(config('app.prefix') . '.process.index');
})->name(config('app.prefix') . '.process');

// Technology
Route::get('/technology', function () {
    return view(config('app.prefix') . '.technology.index');
})->name(config('app.prefix') . '.technology');

// Process
Route::get('/process', function () {
    return view(config('app.prefix') . '.process.index');
})->name(config('app.prefix') . '.process');

// About
Route::get('/about', function () {
    return view(config('app.prefix') . '.about.index');
})->name(config('app.prefix') . '.about');

// Supply Chain

Route::get('/tracking', function () {
    return redirect('https://pipeline.flatworldsc.com/app.php?r=tracking');
});
Route::post('/getTracking', 'ShipmentTrackingController@getTracking')->name('getTracking');

// Solutions
Route::get('/solutions', function () {
    return view(config('app.prefix') . '.solutions.index');
})->name(config('app.prefix') . '.solutions');

Route::get('/solutions/ltl', function () {
    return view(config('app.prefix') . '.solutions.ltl');
})->name(config('app.prefix') . '.solutions.ltl');

Route::get('/solutions/tl', function () {
    return view(config('app.prefix') . '.solutions.tl');
})->name(config('app.prefix') . '.solutions.tl');

Route::get('/solutions/hospitality', function () {
    return view(config('app.prefix') . '.solutions.hospitality');
})->name(config('app.prefix') . '.solutions.hospitality');

Route::get('/solutions/expedited', function () {
    return view(config('app.prefix') . '.solutions.expedited');
})->name(config('app.prefix') . '.solutions.expedited');

Route::get('/solutions/international', function () {
    return view(config('app.prefix') . '.solutions.international');
})->name(config('app.prefix') . '.solutions.international');

Route::get('/solutions/returns', function () {
    return view(config('app.prefix') . '.solutions.returns');
})->name(config('app.prefix') . '.solutions.returns');


// Flat World Global Solutions
Route::get('/solutions/air2post', function () {
    return view(config('app.prefix') . '.solutions.air2post');
})->name(config('app.prefix') . '.solutions.air2post');

Route::get('/solutions/airFreight', function () {
    return view(config('app.prefix') . '.solutions.airFreight');
})->name(config('app.prefix') . '.solutions.airFreight');

Route::get('/solutions/oceanFreight', function () {
    return view(config('app.prefix') . '.solutions.oceanFreight');
})->name(config('app.prefix') . '.solutions.oceanFreight');

Route::get('/solutions/compliance', function () {
    return view(config('app.prefix') . '.solutions.compliance');
})->name(config('app.prefix') . '.solutions.compliance');

Route::get('/solutions/tempControlledCargo', function () {
    return view(config('app.prefix') . '.solutions.tempControlledCargo');
})->name(config('app.prefix') . '.solutions.tempControlledCargo');

Route::get('/solutions/specialtyCargo', function () {
    return view(config('app.prefix') . '.solutions.specialtyCargo');
})->name(config('app.prefix') . '.solutions.specialtyCargo');

Route::get('/solutions/warehousing', function () {
    return view(config('app.prefix') . '.solutions.warehousing');
})->name(config('app.prefix') . '.solutions.warehousing');

Route::get('/solutions/domesticTransportation', function () {
    return view(config('app.prefix') . '.solutions.domesticTransportation');
})->name(config('app.prefix') . '.solutions.domesticTransportation');

Route::get('/solutions/shipmentTracking', function () {
    return view(config('app.prefix') . '.solutions.shipmentTracking');
})->name(config('app.prefix') . '.solutions.shipmentTracking');

Route::get('/terms', function () {
    return view(config('app.prefix') . '.termsConditions.index');
})->name(config('app.prefix') . '.terms');

Route::get('/resources', function () {
    return view(config('app.prefix') . '.resources.index');
})->name(config('app.prefix') . '.resources');

// E-Commerce Routes
Route::get('/ecommerce', function () {
    return view(config('app.prefix') . '.solutions.ecommerce');
})->name(config('app.prefix') . '.ecommerce');

Route::get('/solutions/ecommerceQuote/lineItem', function () {
    return view(config('app.prefix') . '.solutions.ecommerceQuote.lineItem');
})->name(config('app.prefix') . '.ecommerce.lineItem');

Route::get('/solutions/ecommerceQuote/cartonCrate', function () {
    return view(config('app.prefix') . '.solutions.ecommerceQuote.cartonCrate');
})->name(config('app.prefix') . '.ecommerce.cartonCrate');

Route::get('/solutions/ecommerceQuote/cartonPallet', function () {
    return view(config('app.prefix') . '.solutions.ecommerceQuote.cartonPallet');
})->name(config('app.prefix') . '.ecommerce.cartonPallet');

Route::post('/eCommerceForm', 'ECommerceFormController@sendEmail')->name('eCommerceForm');

Route::get('/profile/signatures/download/{signature}', 'EmailSignatureController@renderHtml')->name('signatures.download');
Route::resource('/profile/signatures', 'EmailSignatureController');

Auth::routes();

Route::get('/playground', function () {
    return view('playground');
})->name('playground');

Route::get('/api/companies', 'CompanyController@index');

// Route::get('/', 'HomeController@index')->name('home');

// Temp routes
Route::get('/alert', function () {
    return view(config('app.prefix') . '.alerts.indiaAlert');
});

// Api
Route::namespace('Api')->name('api.')->prefix('api')->group(function () {
    // Blog Routes
    Route::get('blog/{blog}/restore', 'BlogApiController@restore')->name('blog.restore');
    Route::get('blog/{blog}/delete', 'BlogApiController@delete')->name('blog.delete');
    Route::resource('blog', 'BlogApiController');

    // Career Routes
    Route::resource('career', 'CareerController');

    // Tracking
    Route::post('tracking/{trackingNumber}', 'TrackingApiController@getTracking')->name('tracking');
});

Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () {
    // Blog Admin
    Route::resource('blog', 'BlogAdminController');

    // Career Admin
    Route::resource('career', 'CareerController');
});

// Temp route to test emails
Route::get('mailable', function (Request $request) {
    return new App\Mail\EcommerceResponderForm($request);
})->name('mailable');

// Temp routes
Route::get('/review-map', function () {
    return view('temp.review');
});

app/Blog.php
<?php

namespace App;

use App\Traits\Filters\FilterByCompanyTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Blog extends Model
{

    use SoftDeletes;
    use FilterByCompanyTrait;

    /**
    * The attributes that should be mutated to dates.
    *
    * @var array
    */

    protected $dates = ['deleted_at'];

    public function company() {
        return $this->belongsTo('App\Company', 'company_id', 'id');
    }

    public function user() {
        return $this->belongsTo('App\User', 'created_by', 'id');
    }

    public function getRouteKeyName() {
        return 'slug';
    }

}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\ImageManager;
use Validator;
use Entrust;
use App\Blog;
use App\Company;
use Storage;
use Image;
use Brand;
use Session;

class BlogController extends Controller
{
    public function index()
    {
        // Start blog query builder
        $BLOG_QUERY = Blog::with('company');

        $blogs = $BLOG_QUERY
            ->orderBy('created_at', 'desc')
            ->where('published', 1)
            ->paginate(9);

        return view('blog.index', [
            'blogs' => $blogs,
        ]);
    }

    public function show(Blog $blog)
    {
        return view('blog.show')->withBlog($blog);
    }
}

resources/views/blog/create.blade.php
@extends('app.updated-layout')

@section('title', '[New] Blog | ')

@section('content')

    @if ($errors->any())
    <div class="message-flash critical">
        <span class="close" data-toggle="hide-parent">
            <fw-font-awesome-icon icon="times"></fw-font-awesome-icon>
            {{-- <i class="far fa-times fa-fw"></i> --}}
        </span>
        <div>
            @foreach ($errors->all() as $error)
            <span class="response__heading" style="display: block; text-align: left;">{{ $error }}</span>
            @endforeach
        </div>
    </div>
    @endif

    <h1 class="blog__title">Create New Blog Post</h1>

    <form action="{{ route('blog.store') }}" method="POST" enctype="multipart/form-data">
        @method('POST')
        @csrf

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Title and Featured Image</h2>

        <div class="form-group">
            <label for="title" @if ($errors->has('title')) class="error" @endif>
                <div class="label-text">Post Title</div>
                <input type="text" name="title" id="title" value="{{ old('title') }}" placeholder="Post Title" required>
            </label>

            <label for="featured_image" @if ($errors->has('featured_image')) class="error" @endif>
                <span class="label-text">Featured Image</span>
                <input type="file" name="featured_image" id="featured_image" required>
            </label>
        </div>

        <div class="form-group">
            <label for="summary" @if ($errors->has('summary')) class="error" @endif>
                <span class="label-text">Post Summary</span>
                <textarea name="summary" id="summary" rows="3" placeholder="Drop in a short description about this post." required>{{ old('summary') }}</textarea>
            </label>
        </div>

        <div class="form-group">
            <label for="content" @if ($errors->has('content')) class="error" @endif>
                <span class="label-text">Post Content</span>
                <textarea name="content" id="post_content" rows="10" placeholder="Please be as descriptive as possible." required>{{ old('content') }}</textarea>
            </label>
        </div>

        @role(['developer', 'super.admin'])
        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">What company does this need to post on?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('company')) class="error" @endif>
                @foreach($companies as $company)
                <label class="radio" for="{{ $company->shortname }}">
                    <input type="radio" name="{{ $company->shortname }}" id="{{ $company->shortname }}" value="{{ $company->id }}" required>
                    <span class="label-text">{{ $company->name }}</span>
                </label>
                @endforeach
            </fieldset>
        </div>
        @endrole



        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Do you want this to post now?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('published')) class="error" @endif>
                <label class="inputGroup radio" for="published">
                    <input type="radio" name="published" id="published" value="1" required>
                    <span class="label-text">Published</span>
                </label>

                <label class="inputGroup radio" for="draft">
                    <input type="radio" name="published" id="draft" value="0" required>
                    <span class="label-text">Draft</span>
                </label>
            </fieldset>
        </div>

        <div style="display: flex; flex-flow: row nowrap; justify-content: flex-end; margin: 12px 0 0; padding: 0 12px;">
            <fw-link href="{{ route('blog.index') }}" design="text" state="critical" size="small" icon="times" style="margin: 0 16px 0 0;">
                Cancel
            </fw-link>

            <fw-button design="solid" state="info" size="small" icon="paper-plane" type="submit" role="button">
                Post Blog
            </fw-button>
        </div>

    </form>

@endsection

resources/views/blog/edit.blade.php
@extends('app.updated-layout')

@section('title', '[Edit] ' . $blog->title . ' | ')

@section('content')

    @if ($errors->any())
    <div class="message-flash critical">
        <span class="close" data-toggle="hide-parent">
            <fw-font-awesome-icon icon="times"></fw-font-awesome-icon>
            {{-- <i class="far fa-times fa-fw"></i> --}}
        </span>
            @foreach ($errors->all() as $error)
            <span class="response__heading">{{ $error }}</span>
            @endforeach
    </div>
    @endif

    <h1 class="blog__title">Edit Post</h1>

    <form action="{{ route('blog.update', ['blog' => $blog->id]) }}" method="post" enctype="multipart/form-data">
        @method('PATCH')
        @csrf

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Title and Featured Image</h2>

        <div class="form-group">
            <label for="title" @if ($errors->has('title')) class="error" @endif>
                <span class="label-text">Post Title</span>
                <input type="text" name="title" id="title" value="{{ $blog->title }}" placeholder="Post Title" required>
            </label>

            <label for="featured_image" data-hover="image" data-url="{{ $blog->featured_image }}" @if ($errors->has('featured_image')) class="error" @endif>
                <span class="label-text">Featured Image</span>
                <input type="file" name="featured_image" id="featured_image">
            </label>
        </div>

        <div class="form-group">
            <label for="summary" @if ($errors->has('summary')) class="error" @endif>
                <span class="label-text">Post Summary</span>
                <textarea name="summary" id="summary" value="" rows="3" placeholder="Drop in a short description about this post." required>{{ $blog->summary }}</textarea>
            </label>
        </div>

        <div class="form-group">
            <label for="content" @if ($errors->has('content')) class="error" @endif>
                <span class="label-text">Post Content</span>
                <textarea name="content" id="post_content" value="" rows="10" placeholder="Please be as descriptive as possible." required>{{ $blog->content }}</textarea>
            </label>
        </div>

        @role(['developer', 'super.admin'])
        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">What company does this need to post on?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('company')) class="error" @endif>
                @foreach($companies as $company)
                <label class="radio" for="{{ $company->shortname }}">
                    @if($company->id == $blog->company_id)
                    <input type="radio" name="company_id" id="{{ $company->shortname }}" value="{{ $company->id }}" checked required>
                    @else
                    <input type="radio" name="company_id" id="{{ $company->shortname }}" value="{{ $company->id }}" required>
                    @endif
                    <span class="label-text">{{ $company->name }}</span>
                </label>
                @endforeach
            </fieldset>
        </div>
        @endrole

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Do you want this to post now?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('published')) class="error" @endif>
                <label class="inputGroup radio" for="published">
                    @if ($blog->published === 1)
                    <input type="radio" name="published" id="published" value="1" checked required>
                    @else
                    <input type="radio" name="published" id="published" value="1" required>
                    @endif
                    <span class="label-text">Published</span>
                </label>

                <label class="inputGroup radio" for="draft">
                    @if ($blog->published === 0)
                    <input type="radio" name="published" id="draft" value="0" checked required>
                    @else
                    <input type="radio" name="published" id="draft" value="0" required>
                    @endif
                    <span class="label-text">Draft</span>
                </label>
            </fieldset>
        </div>

        <div style="display: flex; flex-flow: row nowrap; justify-content: flex-end; margin: 12px 0 0; padding: 0 12px;">
            <fw-link href="{{ route('blog.index') }}" design="text" state="critical" size="small" icon="times" style="margin: 0 16px 0 0;">
                Cancel
            </fw-link>

            <fw-button design="solid" state="info" size="small" icon="paper-plane" type="submit" role="button">
                Update Post
            </fw-button>
        </div>

    </form>

@endsection

resources/views/blog/index.blade.php
@extends('app.updated-layout')

@section('title', 'Blog | ')

@section('content')

    <h1 class="page__title my-1">{{ Brand::name() }} Blog</h1>

    <h3 class="page__subTitle my-1">Keep up-to-date with the latest news from Flat World Global Solutions. Check in for our weekly news post.</h3>


    <div class="d-flex flex-row flex-wrap justify-content-around" style="margin: 64px 0 24px;">

        @foreach ($blogs as $blog)
        <fw-card-blog
            featured-image="{{ $blog->featured_image }}"
            image-alt="Blog image"
            title="{{ $blog->title }}"
            summary="{{ $blog->summary }}"
            created-at="{{ $blog->created_at }}"
            company="{{ $blog->company->name }}"
            href="{{ route('blog.show', ['blog' => $blog->slug]) }}"
        >
        </fw-card-blog>
        @endforeach

    </div>

    {{ $blogs->links('components.paginator') }}

@endsection

resources/views/blog/show.blade.php
@extends('app.updated-layout')

@section('title', $blog->title.' | ')

@section('meta')
<meta property="og:title" content="{{ $blog->title }}">
<meta property="og:description" content="{{ $blog->summary }}">
<meta property="og:image" content="{{ $blog->featured_image }}">
<meta property="og:site_name" content="{{ config('app.name') }}">
@endsection

@section('content')

    <div class="blog__hero">
        <img src="{{ $blog->featured_image }}" alt="{{ $blog->title }} hero image.">
    </div>

    <div class="blog__content">
        <div class="blog__meta">
            Posted on
            <span>{{ date('F d, Y', strtotime($blog->created_at)) }}</span>
        </div>

        <h1 class="blog__title">{{ $blog->title }}</h1>

        <h3 class="blog__summary">{{ $blog->summary }}</h3>

        <div class="addthis_inline_share_toolbox" style="margin: 0 0 0 -7px;"></div>

        <hr
            style="
                border-color: rgba(0,0,0,.1);
                border-width: 1px;
                border-bottom: none;
            "
        >

        <div class="blog__body markdown">

            @markdown($blog->content)

        </div>
    </div>

@endsection

@section('footer-scripts')
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5c4a2f08a740f59b"></script>
@endsection