routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Helpers\Brand;
use Illuminate\Http\Request;

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('/login-failed', function () {
    return view('auth.fail');
});

Route::get('/', function () {
    return view(config('app.prefix') . '.home.index');
})->name('home');

// Password Reset Routes
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// User Management Routes
Route::resource('/user', 'UserManagementController');

// User Profile Routes
Route::get('/profile', 'UserProfileController@index')->name('userProfile.index');
Route::get('/profile/edit', 'UserProfileController@edit')->name('userProfile.edit');
Route::patch('/profile/update', 'UserProfileController@update')->name('userProfile.update');

Route::get('/profile/password', 'ChangePasswordController@index')->name('changePassword.index');
Route::post('/changePassword', 'ChangePasswordController@changePassword')->name('changePassword.changePassword');

// Contact
Route::resource('/contact', 'ContactController');
Route::post('/air2PostContact', 'ContactController@a2PStoreContact')->name('air2PostContact');
// Route::get('/contact', function () {
//     return view(config('app.prefix').'.contact.index');
// })->name('contact');

Route::post('/generalContact', 'GeneralContactController@sendEmail')->name('generalContact');

// Careers
Route::resource('/careers', 'CareerController');
Route::get('/careers/delete/{id}', 'CareerController@delete')->name('careers.delete');

// Blog Public
Route::get('/blog', 'BlogController@index')->name('blog.index');
Route::get('/blog/{blog}', 'BlogController@show')->name('blog.show');

// Pages
Route::get('/pages/{pages}/restore', 'PageController@restore')->name('pages.restore');
Route::resource('/pages', 'PageController');
Route::get('/pages/delete/{pages}', 'PageController@delete')->name('pages.delete');

// Image Uploads
Route::get('/api/images', 'ImageUploadController@index');
Route::post('/api/images/store', 'ImageUploadController@store');

// Services
Route::get('/services', function () {
    return view(config('app.prefix') . '.services.index');
})->name(config('app.prefix') . '.services');

// Software
Route::get('/software', function () {
    return view(config('app.prefix') . '.software.index');
})->name(config('app.prefix') . '.software');

// Services
Route::get('/process', function () {
    return view(config('app.prefix') . '.process.index');
})->name(config('app.prefix') . '.process');

// Technology
Route::get('/technology', function () {
    return view(config('app.prefix') . '.technology.index');
})->name(config('app.prefix') . '.technology');

// Process
Route::get('/process', function () {
    return view(config('app.prefix') . '.process.index');
})->name(config('app.prefix') . '.process');

// About
Route::get('/about', function () {
    return view(config('app.prefix') . '.about.index');
})->name(config('app.prefix') . '.about');

// Supply Chain

Route::get('/tracking', function () {
    return redirect('https://pipeline.flatworldsc.com/app.php?r=tracking');
});
Route::post('/getTracking', 'ShipmentTrackingController@getTracking')->name('getTracking');

// Solutions
Route::get('/solutions', function () {
    return view(config('app.prefix') . '.solutions.index');
})->name(config('app.prefix') . '.solutions');

Route::get('/solutions/ltl', function () {
    return view(config('app.prefix') . '.solutions.ltl');
})->name(config('app.prefix') . '.solutions.ltl');

Route::get('/solutions/tl', function () {
    return view(config('app.prefix') . '.solutions.tl');
})->name(config('app.prefix') . '.solutions.tl');

Route::get('/solutions/hospitality', function () {
    return view(config('app.prefix') . '.solutions.hospitality');
})->name(config('app.prefix') . '.solutions.hospitality');

Route::get('/solutions/expedited', function () {
    return view(config('app.prefix') . '.solutions.expedited');
})->name(config('app.prefix') . '.solutions.expedited');

Route::get('/solutions/international', function () {
    return view(config('app.prefix') . '.solutions.international');
})->name(config('app.prefix') . '.solutions.international');

Route::get('/solutions/returns', function () {
    return view(config('app.prefix') . '.solutions.returns');
})->name(config('app.prefix') . '.solutions.returns');


// Flat World Global Solutions
Route::get('/solutions/air2post', function () {
    return view(config('app.prefix') . '.solutions.air2post');
})->name(config('app.prefix') . '.solutions.air2post');

Route::get('/solutions/airFreight', function () {
    return view(config('app.prefix') . '.solutions.airFreight');
})->name(config('app.prefix') . '.solutions.airFreight');

Route::get('/solutions/oceanFreight', function () {
    return view(config('app.prefix') . '.solutions.oceanFreight');
})->name(config('app.prefix') . '.solutions.oceanFreight');

Route::get('/solutions/compliance', function () {
    return view(config('app.prefix') . '.solutions.compliance');
})->name(config('app.prefix') . '.solutions.compliance');

Route::get('/solutions/tempControlledCargo', function () {
    return view(config('app.prefix') . '.solutions.tempControlledCargo');
})->name(config('app.prefix') . '.solutions.tempControlledCargo');

Route::get('/solutions/specialtyCargo', function () {
    return view(config('app.prefix') . '.solutions.specialtyCargo');
})->name(config('app.prefix') . '.solutions.specialtyCargo');

Route::get('/solutions/warehousing', function () {
    return view(config('app.prefix') . '.solutions.warehousing');
})->name(config('app.prefix') . '.solutions.warehousing');

Route::get('/solutions/domesticTransportation', function () {
    return view(config('app.prefix') . '.solutions.domesticTransportation');
})->name(config('app.prefix') . '.solutions.domesticTransportation');

Route::get('/solutions/shipmentTracking', function () {
    return view(config('app.prefix') . '.solutions.shipmentTracking');
})->name(config('app.prefix') . '.solutions.shipmentTracking');

Route::get('/terms', function () {
    return view(config('app.prefix') . '.termsConditions.index');
})->name(config('app.prefix') . '.terms');

Route::get('/resources', function () {
    return view(config('app.prefix') . '.resources.index');
})->name(config('app.prefix') . '.resources');

// E-Commerce Routes
Route::get('/ecommerce', function () {
    return view(config('app.prefix') . '.solutions.ecommerce');
})->name(config('app.prefix') . '.ecommerce');

Route::get('/solutions/ecommerceQuote/lineItem', function () {
    return view(config('app.prefix') . '.solutions.ecommerceQuote.lineItem');
})->name(config('app.prefix') . '.ecommerce.lineItem');

Route::get('/solutions/ecommerceQuote/cartonCrate', function () {
    return view(config('app.prefix') . '.solutions.ecommerceQuote.cartonCrate');
})->name(config('app.prefix') . '.ecommerce.cartonCrate');

Route::get('/solutions/ecommerceQuote/cartonPallet', function () {
    return view(config('app.prefix') . '.solutions.ecommerceQuote.cartonPallet');
})->name(config('app.prefix') . '.ecommerce.cartonPallet');

Route::post('/eCommerceForm', 'ECommerceFormController@sendEmail')->name('eCommerceForm');

Route::get('/profile/signatures/download/{signature}', 'EmailSignatureController@renderHtml')->name('signatures.download');
Route::resource('/profile/signatures', 'EmailSignatureController');

Auth::routes();

Route::get('/playground', function () {
    return view('playground');
})->name('playground');

Route::get('/api/companies', 'CompanyController@index');

// Route::get('/', 'HomeController@index')->name('home');

// Temp routes
Route::get('/alert', function () {
    return view(config('app.prefix') . '.alerts.indiaAlert');
});

// Api
Route::namespace('Api')->name('api.')->prefix('api')->group(function () {
    // Blog Routes
    Route::get('blog/{blog}/restore', 'BlogApiController@restore')->name('blog.restore');
    Route::get('blog/{blog}/delete', 'BlogApiController@delete')->name('blog.delete');
    Route::resource('blog', 'BlogApiController');

    // Career Routes
    Route::resource('career', 'CareerController');

    // Tracking
    Route::post('tracking/{trackingNumber}', 'TrackingApiController@getTracking')->name('tracking');
});

Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function () {
    // Blog Admin
    Route::resource('blog', 'BlogAdminController');

    // Career Admin
    Route::resource('career', 'CareerController');
});

// Temp route to test emails
Route::get('mailable', function (Request $request) {
    return new App\Mail\EcommerceResponderForm($request);
})->name('mailable');

// Temp routes
Route::get('/review-map', function () {
    return view('temp.review');
});

resources/views/pages/create.blade.php
@extends('app.updated-layout')

@section('title', '[New] Page | ')

@section('content')

    @if ($errors->any())
    <div class="message-flash critical">
        <span class="close" data-toggle="hide-parent"><fw-font-awesome-icon icon="times"></fw-font-awesome-icon></span>
        <div>
            @foreach ($errors->all() as $error)
            <span class="response__heading" style="display: block; text-align: left;">{{ $error }}</span>
            @endforeach
        </div>
    </div>
    @endif

    <h1 class="blog__title">Create New Page</h1>

    <form action="{{ route('pages.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Title and Featured Image</h2>

        <div class="form-group">
            <label for="title" @if ($errors->has('title')) class="error" @endif>
                <span class="label-text">Post Title</span>
                <input type="text" name="title" id="title" value="{{ old('title') }}" placeholder="Post Title" required>
            </label>

            <label for="featured_image" @if ($errors->has('featured_image')) class="error" @endif>
                <span class="label-text">Featured Image</span>
                <input type="file" name="featured_image" id="featured_image" required>
            </label>
        </div>

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Gallery Images</h2>

        <div class="form-group">

            <label for="images[]" @if ($errors->has('images')) class="error" @endif>
                <span class="label-text">Gallery Images</span>
                <input type="file" name="images[]" id="featured_image" multiple required>
            </label>

        </div>

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Page Content</h2>

        <div class="form-group">
            <label for="summary" @if ($errors->has('summary')) class="error" @endif>
                <span class="label-text">Post Summary</span>
                <textarea name="summary" id="summary" rows="3" placeholder="Drop in a short description about this post." required>{{ old('summary') }}</textarea>
            </label>
        </div>

        <div class="form-group">
            <label for="content" @if ($errors->has('content')) class="error" @endif>
                <span class="label-text">Post Content</span>
                <textarea name="content" id="post_content" rows="10" placeholder="Please be as descriptive as possible." required>{{ old('content') }}</textarea>
            </label>
        </div>

        @role(['developer', 'super.admin'])
        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">What company does this need to post on?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('company')) class="error" @endif>
                @foreach($companies as $company)
                <label class="radio" for="{{ $company->shortname }}">
                    <input type="radio" name="{{ $company->shortname }}" id="{{ $company->shortname }}" value="{{ $company->id }}" required>
                    <span class="label-text">{{ $company->name }}</span>
                </label>
                @endforeach
            </fieldset>
        </div>
        @endrole



        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Do you want this to post now?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('published')) class="error" @endif>
                <label class="inputGroup radio" for="published">
                    <input type="radio" name="published" id="published" value="1" required>
                    <span class="label-text">Published</span>
                </label>

                <label class="inputGroup radio" for="draft">
                    <input type="radio" name="published" id="draft" value="0" required>
                    <span class="label-text">Draft</span>
                </label>
            </fieldset>
        </div>

        <div style="display: flex; flex-flow: row nowrap; justify-content: flex-end; margin: 12px 0 0; padding: 0 12px;">
            <fw-link href="{{ route('pages.index') }}" design="text" state="critical" size="small" icon="times" style="margin: 0 16px 0 0;">
                Cancel
            </fw-link>

            <fw-button design="solid" state="info" size="small" icon="paper-plane" type="submit" role="button">
                Post Page
            </fw-button>
        </div>

    </form>

@endsection

resources/views/pages/edit.blade.php
@extends('app.updated-layout')

@section('title', '[Edit] Page | ')

@section('content')

    <h1 class="blog__title">Edit Page</h1>

    <form action="{{ route('pages.update', ['page' => $page->id]) }}" method="POST" enctype="multipart/form-data">
        @method('PATCH')
        @csrf


        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Title and Featured Image</h2>

        <div class="form-group">
            <label for="title" @if ($errors->has('title')) class="error" @endif>
                <span class="label-text">Post Title</span>
                <input type="text" name="title" id="title" value="{{ $page->title }}" placeholder="Post Title" required>
            </label>

            <label for="featured_image" @if ($errors->has('featured_image')) class="error" @endif>
                <span class="label-text">Featured Image</span>
                <input type="file" name="featured_image" id="featured_image">
            </label>
        </div>

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Gallery Images</h2>

        <div class="form-group">

            <label for="images[]" @if ($errors->has('images')) class="error" @endif>
                <span class="label-text">Gallery Images</span>
                <input type="file" name="images[]" id="featured_image" multiple required>
            </label>

        </div>

        <div class="d-flex flex-row overflow-x mb-4">
            @foreach($images as $image)
                @component('components.cards.general', [
                    'cardClasses' => 'medium heroOnly no-flex-shrink mr-2',
                    'hasShadow' => true,
                    'isAnimated' => true,
                    'hasHero' => true,
                    'hasAdminControls' => true,
                    'heroImageClasses' => 'cover center',
                    'heroImageSource' => $image->url,
                    'deleteLink' => route('image.delete', ['id' => $image->id]),
                ])
                @endcomponent
            @endforeach
        </div>

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Page Content</h2>

        <div class="form-group">
            <label for="summary" @if ($errors->has('content')) class="error" @endif>
                <span class="label-text">Post Summary</span>
                <textarea name="summary" id="summary" rows="3" placeholder="Drop in a short description about this post." required>{{ $page->summary }}</textarea>
            </label>
        </div>

        <div class="form-group mb-4">
            <label for="content" @if ($errors->has('content')) class="error" @endif>
                <span class="label-text">Post Content</span>
                <textarea name="content" id="post_content" rows="10" placeholder="Please be as descriptive as possible." required>{{ $page->content }}</textarea>
            </label>
        </div>

        @role(['developer', 'super.admin'])
        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">What company does this need to post on?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('company')) class="error" @endif>
                @foreach($companies as $company)
                <label class="radio" for="{{ $company->shortname }}">
                    @if($company->id == $page->company_id)
                    <input type="radio" name="company_id" id="{{ $company->shortname }}" value="{{ $company->id }}" checked required>
                    @else
                    <input type="radio" name="company_id" id="{{ $company->shortname }}" value="{{ $company->id }}" required>
                    @endif
                    <span class="label-text">{{ $company->name }}</span>
                </label>
                @endforeach
            </fieldset>
        </div>
        @endrole

        <h2 class="mt-5 mb-1" style="padding: 0 0 0 12px;">Do you want this to post now?</h2>

        <div class="form-group">
            <fieldset @if ($errors->has('published')) class="error" @endif>
                <label class="inputGroup radio" for="published">
                    @if ($page->published === 1)
                    <input type="radio" name="published" id="published" value="1" checked required>
                    @else
                    <input type="radio" name="published" id="published" value="1" required>
                    @endif
                    <span class="label-text">Published</span>
                </label>

                <label class="inputGroup radio" for="draft">
                    @if ($page->published === 0)
                    <input type="radio" name="published" id="draft" value="0" checked required>
                    @else
                    <input type="radio" name="published" id="draft" value="0" required>
                    @endif
                    <span class="label-text">Draft</span>
                </label>
            </fieldset>
        </div>

        <div style="display: flex; flex-flow: row nowrap; justify-content: flex-end; margin: 12px 0 0; padding: 0 12px;">
            <fw-link href="{{ route('pages.index') }}" design="text" state="critical" size="small" icon="times" style="margin: 0 16px 0 0;">
                Cancel
            </fw-link>

            <fw-button design="solid" state="info" size="small" icon="paper-plane" type="submit" role="button">
                Update Page
            </fw-button>
        </div>
    </form>

@endsection

resources/views/pages/index.blade.php
@extends('app.updated-layout')

@section('title', 'Pages | ')

@section('content')

@if (Entrust::hasRole(['developer', 'super.admin']))
<h1 class="page__title my-1">Flat World Public Sites - Pages</h1>
@else
<h1 class="page__title my-1">{{ Brand::name() }} Pages</h1>
@endif

<h3 class="page__subTitle my-1">Content pages generated by </h3>

@if (Auth::check())
<div class="d-flex flex-row justify-content-between">
    <fw-link href="{{ route('pages.create') }}" target="_self" design="solid" state="info" size="small" icon="plus">
        Create New Page
    </fw-link>

    <fw-link href="{{ route('logout') }}" target="_self" design="solid" state="dark" size="small" icon="sign-out">
        Log Out
    </fw-link>
</div>
@endif

<div class="d-flex flex-row flex-wrap justify-content-around mt-5 mb-5">

    @foreach($pages as $page)
        @component ('components.cards.general', [
            'cardClasses' => 'medium header mx-2 mb-5',
            'hasHero' => true,
            'companyName' => $page->company->name,
            'heroImageSource' => $page->featured_image,
            'heroImageClasses' => 'cover center',
            'hasShadow' => true,
            'isAnimated' => true,
            'hasAdminControls' => $pagePermission,
            'hasContent' => true,
            'hasDivider' => true,
            'hasFooter' => true,
            'hasActions' => true,
            'cardHeading' => str_limit($page->title, 40),
            'headingClasses' => 'text heading h5 font-weight-800 center uppercase',
            'cardText' => str_limit($page->summary, 75),
            'textClasses' => 'text paragraph small font-weight-400 center mb-5',
            'actions' => [
                [
                    'text' => 'Read More',
                    'link' => route('pages.show', ['page' => $page->id]),
                    'classes' => 'link',
                ]
            ]
        ])

            @if (empty($page->deleted_at))
                @permission ('update.site.page')
                    @slot('editLink')
                    {{ route('pages.edit', ['page' => $page->id]) }}
                    @endslot
                @endpermission

                @permission ('delete.site.page')
                    @slot('deleteLink')
                    {{ route('pages.delete', ['page' => $page->id]) }}
                    @endslot
                @endpermission
            @endif

            @if (! empty($page->deleted_at))
            @role (['developer', 'super.admin'])
                @slot('restoreLink')
                {{ route('pages.restore', ['page' => $page->id]) }}
                @endslot
            @endrole
            @endif


            @slot('publishStatus')
                @if(! empty($page->deleted_at))
                Deleted
                @elseif($page->published == 0)
                Draft
                @elseif($page->published == 1)
                Published
                @endif
            @endslot
        @endcomponent
    @endforeach

</div>

@endsection

resources/views/pages/show.blade.php
@extends('app.updated-layout') 
@section('content') @if (Auth::check())
<fw-link href="{{ route('pages.edit', ['page' => $page->id]) }}" target="_self" design="solid" state="info" size="small"
    icon="edit">
    Edit This Page
</fw-link>
@endif

<h1 class="page__title my-1">{{ $page->title }}</h1>

<h3 class="page__subTitle my-1">{{ $page->summary }}</h3>

<div class="d-flex flex-column">
    <div class="splashImage blogSplash">

        <h3 class="em">{{ date('F d, Y', strtotime($page->created_at)) }}</h3>

        <img src="{{ $page->featured_image }}" class="imageBg cover center" alt="">

    </div>
</div>

<h2 class="mt-5 mb-4">Image Gallery</h2>

<div class="gallery row">
    @foreach($gallery_images as $gallery_image)
    <a href="{{ $gallery_image->url }}" data-fancybox="gallery">
                <img src="{{ $gallery_image->url }}" alt="">
            </a> @endforeach
</div>

<div class="markdown">

    @markdown($page->content)

</div>
@endsection